project_id = "twoghutcvlfgemadaeez"

[functions.webhook-new-lead]
verify_jwt = false

[functions.webhook-confirmacao]
verify_jwt = false

[functions.oraculo-comercial]
verify_jwt = false

[functions.calculate-lead-score]
verify_jwt = false
